app: demo-cluster-config

infraName: 

region:
availabilityZone:
subnet:
name: gpu-node

cloud: azure
aws:
  instance: g6.2xlarge
azure:
  instance: Standard_NC4as_T4_v3
  imageSku:
  imageVersion:
  resourceGroup:
  networkResourceGroup:
  vNet:
  loadBalancer:
replicas: 1